@echo off
setlocal
echo Starting get_files_today_with_check.bat...
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command "& { $today = (Get-Date).Date; $updatesDir = Join-Path $PWD 'UPDATES'; if (-not (Test-Path $updatesDir)) { New-Item -ItemType Directory -Path $updatesDir -Force | Out-Null }; $numDirs = Get-ChildItem $updatesDir -Directory | Where-Object { $_.Name -match '^\d+$' } | ForEach-Object { [int]$_.Name }; $next = if ($numDirs) { ($numDirs | Measure-Object -Maximum).Maximum + 1 } else { 1 }; $destRoot = Join-Path $updatesDir $next.ToString(); Write-Host ('Destination folder: ' + $destRoot); $existing = @{}; foreach ($dir in $numDirs) { $dirPath = Join-Path $updatesDir $dir.ToString(); Get-ChildItem $dirPath -Recurse -File | ForEach-Object { $relative = $_.FullName.Substring($dirPath.Length + 1); if ($existing.ContainsKey($relative)) { if ($_.LastWriteTime -gt $existing[$relative]) { $existing[$relative] = $_.LastWriteTime } } else { $existing[$relative] = $_.LastWriteTime } } }; $excludeDirs = @('.git', '.vs', 'UPDATES', 'node_modules', '__pycache__', '.idea', '.vscode', 'bin', 'obj'); $files = Get-ChildItem -Recurse -File | Where-Object { $path = $_.FullName; $exclude = $false; foreach ($dir in $excludeDirs) { if ($path -match ('\\' + $dir + '\\')) { $exclude = $true; break } }; -not $exclude }; $count = 0; foreach ($file in $files) { if ($file.CreationTime.Date -eq $today -or $file.LastWriteTime.Date -eq $today) { $relative = $file.FullName.Substring($PWD.Path.Length + 1); $copy = $true; if ($existing.ContainsKey($relative)) { if ($existing[$relative] -ge $file.LastWriteTime) { $copy = $false } }; if ($copy) { $destFile = Join-Path $destRoot $relative; $destDir = Split-Path $destFile -Parent; if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }; Copy-Item -Path $file.FullName -Destination $destFile -Force; $count++; Write-Host ('Copied: ' + $relative) } } }; Write-Host ('Total files copied: ' + $count) }"

echo.
echo Done.
pause